In [1]:
import tensorflow as tf
import keras

In [27]:
layer = keras.layers.GRU(1, stateful=True)
layers_s = keras.layers.GRU(2, return_sequences=True, return_state=True)

In [23]:
tokens = tf.constant([[1, 2.1, 3, 4], [1, 2, 3, 4], [0, 2, 3, 4]])
print(tokens.shape)
inp_tensor = tf.reshape(tokens, (1, 3, 4))
print(layer(inp_tensor))

(3, 4)
tf.Tensor([[-0.6243828]], shape=(1, 1), dtype=float32)


In [28]:
print(layers_s(inp_tensor))

(<tf.Tensor: shape=(1, 3, 2), dtype=float32, numpy=
array([[[ 0.04352026, -0.3750272 ],
        [ 0.10543108, -0.597564  ],
        [ 0.17990828, -0.6830113 ]]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0.17990828, -0.6830113 ], dtype=float32)>)


In [29]:
(output, state) = layers_s(inp_tensor)
print(output)
print(state)

tf.Tensor(
[[[ 0.04352026 -0.3750272 ]
  [ 0.10543108 -0.597564  ]
  [ 0.17990828 -0.6830113 ]]], shape=(1, 3, 2), dtype=float32)
tf.Tensor([ 0.17990828 -0.6830113 ], shape=(2,), dtype=float32)
